### ISSUE TITLE
feat: 회원 가입 API 개발

### ISSUE THREAD

**Issue by sunyou10** [SNUSTHON/TEAM2_BE#7]
## 🚀 Description

- 첫 가입 시 관심분야를 선택하는 api 를 생성하기

## ✅ TODO

- [ ]  topics DB에 항목 추가
- [ ] 첫 가입 시 항목 선택 페이지로 리다이렉트
- [ ] 항목 선택 후 User 의 my_topics , favorite_topics 에 저장
- [ ] 메인 페이지 `/`로 리다이렉트
